#pragma once

#include <sstream>

#include "Common/types.h"
#include "Common/constants.h"
#include "Common/lf_queue.h"

using namespace Common;
namespace Exchange
{
    // enforces no extra padding is generated by the compiler in the following structs as we need to send and receive in this format over the network in the flat binary form
    #pragma pack(push, 1)

    enum class ClientRequestType : uint8_t
    {
        INVALID = 0,
        NEW = 1,
        CANCEL = 2
    };

    // logging purposes
    inline std::string clientRequestTypeToString(ClientRequestType type)
    {
        switch (type) {
            case ClientRequestType::INVALID : return "INVALID";
            case ClientRequestType::NEW : return "NEW";
            case ClientRequestType::CANCEL : return "CANCEL";
        }
        return "UNKNOWN";
    }

    struct MEClientRequest
    {
        ClientRequestType type_ = ClientRequestType::INVALID;
        ClientId clientId_ = ClientId_INVALID;
        TickerId tickerId_ = TickerId_INVALID;
        OrderId orderId_ = OrderId_INVALID;
        Side side_ = Side::INVALID;
        Price price_ = Price_INVALID;
        Qty qty_ = Qty_INVALID;


        auto toString() const
        {
            std::stringstream ss;
            ss << "MEClientRequest"
                << " ["
                << "type: " << clientRequestTypeToString(type_)
                << " client: " << clientIdToString(clientId_)
                << " tickerId: " << tickerIdToString(tickerId_)
                << " orderId: " << orderIdToString(orderId_)
                << " side: " << sideToString(side_)
                << " qty: " << qtyToString(qty_)
                << " price: " << priceToString(price_)
                << "]";
            return ss.str();
        }
    };
    


    #pragma pack(pop)

    using ClientRequestLFQueue = LFQueue<MEClientRequest>;
}